export const columns = [
  {
    title: "ID",
    dataIndex: "id",
    key: "id",
    order: 1,
  },
  {
    title: "Samhita",
    dataIndex: "bookName",
    key: "bookName",
    order: 7,
  },
  {
    title: "Sthana",
    dataIndex: "sthana",
    key: "sthana",
    order: 8,
  },
  {
    title: "Chapter",
    dataIndex: "chapterNumber",
    key: "chapterNumber",
    order: 9,
  },
  {
    title: "Single or Combination Drug",
    dataIndex: "singleOrCombinationDrug",
    key: "singleOrCombinationDrug",
    order: 11,
  },
  {
    title: "Formulation as a Single Drug",
    dataIndex: "formulationAsASingleDrug",
    key: "formulationAsASingleDrug",
    order: 12,
  },
  {
    title: "Formulation as Combination",
    dataIndex: "formulationAsCombination",
    key: "formulationAsCombination",
    order: 13,
  },
  {
    title: "Name of the Combination",
    dataIndex: "nameOfTheCombination",
    key: "nameOfTheCombination",
    order: 14,
  },
  {
    title: "Use- INT/EXT",
    dataIndex: "useExtOrInt",
    key: "useExtOrInt",
    order: 15,
  },
  {
    title: "Uses as Single Drug",
    dataIndex: "usesAsSingleDrug",
    key: "usesAsSingleDrug",
    order: 18,
  },
  {
    title: "Uses as Combination",
    dataIndex: "usesAsCombination",
    key: "usesAsCombination",
    order: 19,
  },
  {
    title: "Drug Name",
    dataIndex: "drugName",
    key: "drugName",
    order: 2,
  },
  {
    title: "Sanskrit Name",
    dataIndex: "sanskritName",
    key: "sanskritName",
    order: 3,
  },
  {
    title: "Latin Name",
    dataIndex: "latinName",
    key: "latinName",
    order: 4,
  },
  {
    title: "Part of Plant Used",
    dataIndex: "partOfPlantUsed",
    key: "partOfPlantUsed",
    order: 6,
  },
  {
    title: "Type of Ext Use",
    dataIndex: "typeOfExtUse",
    key: "typeOfExtUse",
    order: 16,
  },
  {
    title: "Parenteral Route",
    dataIndex: "parenteralRoute",
    key: "parenteralRoute",
    order: 17,
  },
  {
    title: "Anupana",
    dataIndex: "anupana",
    key: "anupana",
    order: 20,
  },
  {
    title: "Sahapana",
    dataIndex: "sahapana",
    key: "sahapana",
    order: 21,
  },
  {
    title: "Granthadikara",
    dataIndex: "granthadikara",
    key: "granthadikara",
    order: 22,
  },
  {
    title: "Rogadhikara",
    dataIndex: "rogadhikara",
    key: "rogadhikara",
    order: 23,
  },
  {
    title: "Verse Number",
    dataIndex: "verseNumber",
    key: "verseNumber",
    order: 10,
  },
  {
    title: "Remarks",
    dataIndex: "remarks",
    key: "remarks",
    order: 5,
  },
  {
    title: "Actions",
    dataIndex: "actions",
    key: "actions",
    order: 24,
  },
].sort((a, b) => a.order - b.order);

export const pageSize = 100;

export const chapterNumberOptions = [
  "Chapter 1",
  "Chapter 2",
  "Chapter 3",
  "Chapter 4",
  "Chapter 5",
  "Chapter 6",
  "Chapter 7",
  "Chapter 8",
  "Chapter 9",
  "Chapter 10",
  "Chapter 11",
  "Chapter 12",
  "Chapter 13",
  "Chapter 14",
  "Chapter 15",
  "Chapter 16",
  "Chapter 17",
  "Chapter 18",
  "Chapter 19",
  "Chapter 20",
  "Chapter 21",
  "Chapter 22",
  "Chapter 23",
  "Chapter 24",
  "Chapter 25",
  "Chapter 26",
  "Chapter 27",
  "Chapter 28",
  "Chapter 29",
  "Chapter 30",
  "Chapter 31",
  "Chapter 32",
  "Chapter 33",
  "Chapter 34",
  "Chapter 35",
  "Chapter 36",
  "Chapter 37",
  "Chapter 38",
  "Chapter 39",
  "Chapter 40",
  "Chapter 41",
  "Chapter 42",
  "Chapter 43",
  "Chapter 44",
  "Chapter 45",
  "Chapter 46",
  "Chapter 47",
  "Chapter 48",
  "Chapter 49",
  "Chapter 50",
]

export const sthanaOptions = [
  "Chikitsa Sthana",
  "Indriya Sthana",
  "Kalpa Sthana",
  "Kalpa siddhi Sthana",
  "Kalpana Sthana",
  "Nidana Sthana",
  "Sharir Sthana",
  "Sidhi Sthana",
  "Sutra Sthana",
  "Uttar Tantra",
  "Vimana Sthana",
]

export const bookNameOptions = [
  "Charaka Samhita",
  "Shushruta Samhita",
  "Ashtang Hridaya",
  "Ashtang Samgraha",
]